### ISSUE TITLE
NPE: End of combat with hard mode Airi

### ISSUE THREAD

**Issue by Ryplinn** [Ryplinn/nightgamesmod#14]
Built from 8e669742b.

Null Pointer Exception upon winning combat with Airi around level 34. I picked all of the "hard mode" options for her. Nothing hangs, but there's no buttons for continued play.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at nightgames.status.PartFucked.lambda$new$0(PartFucked.java:26)
	at nightgames.status.Status.lambda$meetsRequirements$0(Status.java:48)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at nightgames.status.Status.meetsRequirements(Status.java:48)
	at nightgames.characters.Character.lambda$dropStatus$9(Character.java:1415)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at nightgames.characters.Character.dropStatus(Character.java:1416)
	at nightgames.characters.Character.endofbattle(Character.java:2947)
	at nightgames.combat.Combat.end(Combat.java:1403)
	at nightgames.combat.Combat.next(Combat.java:1332)
	at nightgames.combat.Combat.turn(Combat.java:840)
	at nightgames.combat.Combat.resumeNoClearFlag(Combat.java:251)
	at nightgames.combat.Combat.resume(Combat.java:261)
	at nightgames.combat.Combat.lambda$promptNext$24(Combat.java:1774)
	at nightgames.gui.RunnableButton.lambda$new$0(RunnableButton.java:15)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at nightgames.gui.KeyableButton.call(KeyableButton.java:19)
	at nightgames.gui.GUI$2.keyReleased(GUI.java:604)
	at java.awt.Component.processKeyEvent(Component.java:6496)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Ryplinn** [comment]
Character.endofbattle() calls Character.dropStatus(Combat c, Character opponent) with both parameters null. The status.PartFucked() requirement accesses a method of c, which is what triggers the NPE.

Why endofbattle() calls dropStatus() with null parameters, I don't know. Also, it looks like the requirement for PartFucked will never be met -- all return values are false.

It's possible this was fixed in a different branch. I'll investigate further later.

**Comment by Ryplinn** [comment]
Looks like I had the status "Tentacles Fucked" when combat ended. PartFucked with stick=impaler tentacle and hole=pussy.

**Comment by Ryplinn** [comment]
Fix backported with bb4153b.

**Comment by Ryplinn** [comment]
Addendum: Errors like this one preventing gameplay buttons from appearing, leaving the player stuck, is not really what we want. Either recover and continue play, or crash completely.
