### ISSUE TITLE
Crash during threesome

### ISSUE THREAD

**Issue by Ryplinn** [Ryplinn/nightgamesmod#21]
Pet characters may be removed from the character pool before ongoing stance checks, resulting in errors like this:
```
Character not found: imp
=================
Characters in pool:
Human: Player
NPCs:
	Airi
	Jewel
	Eve
	Angel
	Mara
	Maya
	Cassie
	CUSTOM_NPCSamantha
	Yui
	Reyka
	Kat
Other combatants:
none
An error we didn't expect occurred:
nightgames.characters.CharacterPool$CharacterNotFoundException: Character type imp not found in character pool!
	at nightgames.characters.CharacterType.lambda$fromPoolGuaranteed$0(CharacterType.java:62)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at nightgames.characters.CharacterType.fromPoolGuaranteed(CharacterType.java:62)
	at nightgames.stance.Threesome.getDomSexCharacter(Threesome.java:23)
	at nightgames.stance.ReverseXHFDaisyChainThreesome.checkOngoing(ReverseXHFDaisyChainThreesome.java:41)
	at nightgames.combat.Combat.doEndOfTurnUpkeep(Combat.java:392)
	at nightgames.combat.Combat.runCombat(Combat.java:1807)
	at nightgames.global.Match.matchLoop(Match.java:163)
	at nightgames.global.GameState.gameLoop(GameState.java:141)
	at nightgames.global.Main.run(Main.java:102)
	at nightgames.global.Main.main(Main.java:60)
```

**Comment by Ryplinn** [comment]
Actually, I'm pretty sure spawned pets are never added to the pool. Currently the character pool and current combat keep separate otherCombatant lists. I should have the pool check the current combat directly.
